# IPv7-SIMBI configuracion
IPV7_NODE_ID = "A"
IPV7_BIND = "0.0.0.0:9006"
IPV7_PSK = "clave"
IPV7_TUNNEL_DST = "B"
IPV7_TUNNEL_BIND = "ipv7"
IPV7_PEERS = "2:IP_DEL_NOTEBOOK:9002"
IPV7_TRACKER_ADDR = "127.0.0.1:9000"
IPV7_STUN_SERVER = "stun.l.google.com:19302"
IPV7_TUN_DEVICE = "ipv7"
IPV7_TUN_ADDR = "10.0.0.2"
IPV7_TUN_NETMASK = "255.255.255.0"
IPV7_TUN_DEST = "10.0.0.1"
IPV7_TUN_MTU = "1400"
